'use client'

import Link from 'next/link'
import Image from 'next/image'
import { useRouter, useSearchParams } from 'next/navigation'
import { Suspense, useEffect, useState } from 'react'
import useSWR from 'swr'
import { ArrowRight, CheckCircle2, LogOut } from 'lucide-react'
import { useRequireAuth } from '@/src/components/AuthProvider'
import { formatDate, formatTime, getMyBookings, hasHealthSafety, isUpcoming, scheduleLabel, type Booking } from '@/lib/api/booking'
import { getClassName } from '@/lib/data/classes'

type Tab = 'overview' | 'membership' | 'bookings' | 'profile'
function SectionLabel({ children }: { children: React.ReactNode }) { return <p className="text-[11px] font-medium uppercase tracking-[0.24em] text-accent">{children}</p> }
function membershipValue(value: unknown) { return value === undefined || value === null || value === '' ? null : String(value) }

 function DashboardContent()  {
  const router = useRouter(); const searchParams = useSearchParams(); const { user, loading, logout } = useRequireAuth(); const [tab, setTab] = useState<Tab>('overview'); const [loggingOut, setLoggingOut] = useState(false)
  useEffect(() => { const view = searchParams.get('view'); if (view === 'membership' || view === 'bookings' || view === 'profile') setTab(view); else setTab('overview') }, [searchParams])
  const { data: bookings, error, isLoading, mutate } = useSWR<Booking[]>(user ? 'member-bookings' : null, getMyBookings, { revalidateOnFocus: false })
  if (loading || !user) return <main className="flex min-h-[70vh] items-center justify-center text-muted-foreground">Loading your member space...</main>
  const allBookings = bookings || []; const pending = allBookings.find(item => item.paymentStatus === 'PAID' && item.bookingStatus !== 'CONFIRMED'); const upcoming = allBookings.filter(isUpcoming); const firstName = (user.fullName || 'member').split(' ')[0]; const membership = pending?.membership || allBookings.find(item => item.membership)?.membership || null; const membershipStatus = membershipValue(membership?.status)?.toUpperCase() || 'ACTIVE'; const goToClasses = () => router.push('/classes'); const goToBooking = (booking = pending) => booking?.classId ? router.push(`/book?classId=${encodeURIComponent(booking.classId)}`) : goToClasses()
  const handleLogout = async () => { setLoggingOut(true); try { await logout() } finally { router.replace('/login'); setLoggingOut(false) } }
  return <main className="min-h-[75vh] bg-muted/20 px-4 py-12 pb-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-4xl"><header className="mb-10 flex items-start justify-between gap-5"><div><SectionLabel>Member dashboard</SectionLabel><h1 className="mt-3 font-serif text-4xl text-primary sm:text-5xl">Welcome back, {firstName}</h1><p className="mt-3 text-base leading-7 text-muted-foreground">Your studio membership, timetable, and booking details.</p></div><button type="button" aria-label="Log out" onClick={handleLogout} disabled={loggingOut} className="mt-1 inline-flex items-center gap-2 text-xs uppercase tracking-[0.14em] text-muted-foreground hover:text-primary"><LogOut className="h-4 w-4" /><span className="hidden sm:inline">Log out</span></button></header><div className="mb-10 overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><Image src="/sculpt-dashboard-pilates.png" alt="Calm Sculpt LAB Pilates studio" width={1400} height={560} className="h-48 w-full object-cover sm:h-64" priority /></div>{tab === 'overview' && <div className="space-y-6"><section className="border border-border bg-background p-6 sm:p-8"><SectionLabel>Membership</SectionLabel><div className="mt-7 flex flex-wrap items-end justify-between gap-4"><h2 className="font-serif text-3xl text-primary">{membership?.name || 'Membership details unavailable'}</h2><span className="inline-flex items-center gap-2 text-xs font-medium uppercase tracking-[0.14em] text-accent"><span className="h-2 w-2 rounded-full bg-accent" />{membershipStatus}</span></div>{membership && <div className="mt-5 grid gap-4 text-sm text-muted-foreground sm:grid-cols-3">{membershipValue(membership.period) && <p>Period<br /><b className="text-primary">{membership.period}</b></p>}{membershipValue(membership.priceNGN ?? membership.price) && <p>Price<br /><b className="text-primary">₦{Number(membership.priceNGN ?? membership.price).toLocaleString()}</b></p>}{membershipValue(membership.classLimit) && <p>Class limit<br /><b className="text-primary">{membership.classLimit}</b></p>}</div>}<button type="button" onClick={() => setTab('membership')} className="mt-6 inline-flex items-center gap-2 text-sm font-medium text-primary hover:underline">View membership <ArrowRight className="h-4 w-4" /></button></section>
      <section className="border border-primary bg-background p-6 shadow-sm sm:p-8"><SectionLabel>{pending ? 'Continue booking' : 'Upcoming booking'}</SectionLabel>{pending ? <><h2 className="mt-7 font-serif text-3xl text-primary">{pending.classId ? getClassName(pending.classId) : 'Choose your class'}</h2><p className="mt-2 text-sm text-muted-foreground">{pending.schedule ? scheduleLabel(pending.schedule) : 'Your paid membership is ready to configure.'}</p><button type="button" onClick={() => goToBooking(pending)} className="mt-7 inline-flex items-center gap-2 bg-primary px-5 py-3 text-sm font-medium text-primary-foreground">{pending.classId ? 'Continue booking' : 'Choose your class'} <ArrowRight className="h-4 w-4" /></button></> : upcoming[0] ? <BookingDetails booking={upcoming[0]} /> : <><h2 className="mt-7 font-serif text-3xl text-primary">No upcoming booking yet.</h2><p className="mt-2 text-sm text-muted-foreground">Your confirmed classes will appear here.</p></>}</section>
      <HealthStatus booking={pending || upcoming[0]} onAction={() => pending && goToBooking(pending)} /><section className="border-t border-border pt-7"><SectionLabel>Quick actions</SectionLabel><div className="mt-5 grid gap-3 sm:grid-cols-3">{pending ? <button type="button" onClick={() => goToBooking(pending)} className="border border-border bg-background px-4 py-4 text-left text-sm text-primary transition hover:border-primary">{pending.classId ? pending.schedule ? 'Choose start date' : 'Choose your schedule' : 'Choose your class'}</button> : <button type="button" onClick={goToClasses} className="border border-border bg-background px-4 py-4 text-left text-sm text-primary transition hover:border-primary">Book a Class</button>}</div></section></div>}
    {tab === 'membership' && <section className="space-y-8"><section className="border border-border bg-background p-6 sm:p-8"><SectionLabel>Membership</SectionLabel><h2 className="mt-4 font-serif text-4xl text-primary">{membership?.name || 'Membership details unavailable'}</h2><p className="mt-4 inline-flex items-center gap-2 text-xs uppercase tracking-[0.14em] text-accent"><span className="h-2 w-2 rounded-full bg-accent" />{membershipStatus}</p><div className="mt-8 grid gap-5 border-t border-border pt-6 text-sm sm:grid-cols-2">{[['Type', membership?.type], ['Price', membership?.priceNGN ?? membership?.price ? `₦${Number(membership.priceNGN ?? membership.price).toLocaleString()}` : null], ['Period', membership?.period], ['Start date', membership?.startDate && formatDate(membership.startDate)], ['End date', (membership?.endDate || membership?.expiryDate) && formatDate(membership.endDate || membership.expiryDate)], ['Auto renew', membership?.autoRenew === undefined ? null : membership.autoRenew ? 'Enabled' : 'Disabled']].map(([label, value]) => value ? <div key={label}><p className="text-muted-foreground">{label}</p><p className="mt-1 text-primary">{value}</p></div> : null)}</div></section>{membership?.features?.length ? <section><SectionLabel>Features</SectionLabel><ul className="mt-4 space-y-2 text-sm text-primary">{membership.features.map(item => <li key={item}>• {item}</li>)}</ul></section> : null}</section>}
    {tab === 'bookings' && <section><SectionLabel>My bookings</SectionLabel><h2 className="mt-3 font-serif text-4xl text-primary">Booking history</h2>{isLoading ? <p className="mt-8 text-sm text-muted-foreground">Loading your bookings…</p> : error ? <button type="button" onClick={() => mutate()} className="mt-8 text-sm text-destructive underline">We couldn&apos;t load your bookings. Try again.</button> : <div className="mt-8 space-y-3">{allBookings.length ? allBookings.map(item => <BookingRow key={item.id} booking={item} />) : <p className="text-sm text-muted-foreground">No bookings yet.</p>}</div>}</section>}
    {tab === 'profile' && <section><SectionLabel>Profile</SectionLabel><h2 className="mt-3 font-serif text-4xl text-primary">Your details</h2><div className="mt-10 space-y-8 border border-border bg-background p-6 sm:p-8"><dl className="grid gap-5 text-sm sm:grid-cols-2">{[['Full name', user.fullName], ['Email', user.email], ['Phone', user.phone]].map(([label, value]) => value ? <div key={label}><dt className="text-muted-foreground">{label}</dt><dd className="mt-1 text-primary">{value}</dd></div> : null)}</dl><div className="border-t border-border pt-6"><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Account</p><p className="mt-3 text-sm text-primary">{membershipStatus}</p><button type="button" onClick={handleLogout} className="mt-4 inline-flex items-center gap-2 border border-primary px-4 py-3 text-sm text-primary">{loggingOut ? 'Logging out…' : 'Log out'}</button></div></div></section>}</div></main>
}
function BookingDetails({ booking }: { booking: Booking }) { return <div className="mt-7 grid gap-5 text-sm sm:grid-cols-2"><Info label="Class" value={booking.classId ? getClassName(booking.classId) : null} /><Info label="Schedule" value={booking.schedule?.dayOfWeek} /><Info label="Time" value={booking.schedule ? `${formatTime(booking.schedule.startTime)} – ${formatTime(booking.schedule.endTime)}` : null} /><Info label="Instructor" value={booking.schedule?.tutorName} /><Info label="Start date" value={formatDate(booking.bookingDate)} /><Info label="Status" value={booking.bookingStatus} /></div> }
function Info({ label, value }: { label: string; value?: string | null }) { return value ? <div><p className="text-muted-foreground">{label}</p><p className="mt-1 text-primary">{value}</p></div> : null }
function HealthStatus({ booking, onAction }: { booking?: Booking; onAction: () => void }) { const complete = booking && hasHealthSafety(booking); return <section className="border border-border bg-background p-6 sm:p-8"><SectionLabel>Health & safety</SectionLabel><div className="mt-5 flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-serif text-2xl text-primary">{complete ? 'Completed' : 'Action required'}</h2><p className="mt-1 text-sm text-muted-foreground">{complete ? 'Your form is on file.' : 'Complete your form before confirming a booking.'}</p></div>{!complete && booking && <button type="button" onClick={onAction} className="inline-flex items-center gap-2 bg-primary px-4 py-3 text-sm text-primary-foreground">Complete form <ArrowRight className="h-4 w-4" /></button>}</div></section> }
function BookingRow({ booking }: { booking: Booking }) { return <div className="border border-border bg-background p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-serif text-xl text-primary">{booking.classId ? getClassName(booking.classId) : 'Class not selected'}</h3><div className="mt-3 grid gap-2 text-sm text-muted-foreground sm:grid-cols-2"><Info label="Schedule" value={booking.schedule?.dayOfWeek} /><Info label="Time" value={booking.schedule ? `${formatTime(booking.schedule.startTime)} – ${formatTime(booking.schedule.endTime)}` : null} /><Info label="Instructor" value={booking.schedule?.tutorName} /><Info label="Start date" value={formatDate(booking.bookingDate)} /><Info label="Membership" value={booking.membership?.name} /><Info label="Created" value={formatDate(booking.createdAt)} /></div></div><span className="inline-flex items-center gap-2 text-xs uppercase tracking-[0.12em] text-accent"><CheckCircle2 className="h-4 w-4" />{booking.bookingStatus}</span></div></div> }


export default function DashboardPage() {
  return (
    <Suspense
      fallback={
        <main className="flex min-h-[70vh] items-center justify-center text-muted-foreground">
          Loading your member space...
        </main>
      }
    >
      <DashboardContent />
    </Suspense>
  )
}
