'use client'
import { useSearchParams } from 'next/navigation'
import { useState } from 'react'
import AuthForm from '../AuthForm'
import { authApi } from '../../../lib/api/auth'

export function RegisterPage() { const params = useSearchParams(); return <AuthShell><AuthForm mode="register" email={params.get('email') || ''} reference={params.get('reference') || ''} /></AuthShell> }
export function LoginPage() { return <AuthShell><AuthForm mode="login" /></AuthShell> }
export function AuthShell({ children }: { children: React.ReactNode }) { return <main className="flex min-h-[70vh] items-center justify-center bg-background px-4 py-16">{children}</main> }
export function ForgotPasswordPage() { const [email, setEmail] = useState(''); const [sent, setSent] = useState(false); const [error, setError] = useState(''); return <AuthShell><form onSubmit={async e => { e.preventDefault(); try { await authApi.forgotPassword(email); setSent(true) } catch (x) { setError(x instanceof Error ? x.message : 'Unable to send reset email.') } }} className="w-full max-w-md rounded-2xl border border-border bg-card p-8"><p className="mb-2 text-xs uppercase tracking-[0.22em] text-accent">Account recovery</p><h1 className="font-serif text-4xl text-primary">Reset password</h1>{sent ? <p className="mt-5 text-sm leading-6">Check your inbox for a secure password reset link.</p> : <><label className="mt-6 block text-sm">Email<input required type="email" value={email} onChange={e => setEmail(e.target.value)} className="mt-2 w-full rounded-lg border border-input bg-background px-4 py-3" /></label>{error && <p className="mt-3 text-sm text-destructive">{error}</p>}<button className="mt-5 w-full rounded-lg bg-primary px-4 py-3 text-primary-foreground">Send reset link</button></>}</form></AuthShell> }
export function ResetPasswordPage() { const params = useSearchParams(); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); return <AuthShell><form onSubmit={async e => { e.preventDefault(); try { await authApi.resetPassword({ token: params.get('token'), password }); setMessage('Your password has been updated. You can now log in.') } catch (x) { setMessage(x instanceof Error ? x.message : 'Unable to reset password.') } }} className="w-full max-w-md rounded-2xl border border-border bg-card p-8"><h1 className="font-serif text-4xl text-primary">Choose a new password</h1><label className="mt-6 block text-sm">New password<input required minLength={8} type="password" value={password} onChange={e => setPassword(e.target.value)} className="mt-2 w-full rounded-lg border border-input bg-background px-4 py-3" /></label><button className="mt-5 w-full rounded-lg bg-primary px-4 py-3 text-primary-foreground">Update password</button>{message && <p className="mt-4 text-sm text-muted-foreground">{message}</p>}</form></AuthShell> }
export function VerifyEmailPage() { const params = useSearchParams(); return <AuthShell><div className="w-full max-w-md rounded-2xl border border-border bg-card p-8"><h1 className="font-serif text-4xl text-primary">Verify your email</h1><p className="mt-4 text-sm leading-6 text-muted-foreground">We’re confirming your email address. You can return to your account once verification is complete.</p><button onClick={async () => { await authApi.verifyEmail(params.get('token') || ''); }} className="mt-6 rounded-lg bg-primary px-5 py-3 text-primary-foreground">Verify email</button></div></AuthShell> }
