'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { PageHeading, QuickLink, SectionCard, StatCard, StateNotice, StatusBadge, Table } from './components'
import { loadBookings } from './data'
import { displayValue, formatAdminDate, fullName, membershipName, money, reference, statusValue, type AdminResource } from './types'
import type { Booking } from '@/lib/api/booking'

export default function AdminPage({ view }: { view: string }) {
  if (view === 'dashboard') return <Dashboard />
  return <ResourcePage view={view} />
}

function Dashboard() { const [bookings, setBookings] = useState<AdminResource<Booking[]>>({ state: 'loading' }); useEffect(() => { loadBookings().then(setBookings) }, []); const rows = bookings.state === 'ready' && bookings.data ? bookings.data.slice(0, 6).map((booking) => [<span className="font-medium">{fullName(booking)}</span>, <span>{membershipName(booking.membership)}</span>, <span>{displayValue(booking.schedule?.className)}</span>, <span>{displayValue(booking.paymentStatus)}</span>, <StatusBadge value={booking.bookingStatus} />, <span>{formatAdminDate(booking.createdAt)}</span>]) : []
 return <><PageHeading eyebrow="Studio overview" title="Good morning, admin." description="A truthful view of Sculpt LAB operations. The cards and tables below only use data returned by existing backend services." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total members" value="Unavailable" note="Admin endpoint not available" /><StatCard label="Active memberships" value="Unavailable" note="Admin endpoint not available" /><StatCard label="Pending bookings" value={bookings.state === 'ready' ? String(bookings.data?.filter((item) => item.bookingStatus === 'PENDING').length || 0) : 'Unavailable'} note="From your bookings endpoint" /><StatCard label="Confirmed bookings" value={bookings.state === 'ready' ? String(bookings.data?.filter((item) => item.bookingStatus === 'CONFIRMED').length || 0) : 'Unavailable'} note="From your bookings endpoint" /><StatCard label="Paid bookings" value="Unavailable" note="Admin payments endpoint not available" /><StatCard label="Pending payments" value={bookings.state === 'ready' ? String(bookings.data?.filter((item) => item.paymentStatus === 'PENDING').length || 0) : 'Unavailable'} note="From your bookings endpoint" /><StatCard label="Offline payments" value="Unavailable" note="Admin payments endpoint not available" /></div><div className="mt-8 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><SectionCard title="Recent bookings" action={<Link href="/admin/bookings" className="text-sm text-accent hover:underline">View all</Link>}>{bookings.state === 'ready' && rows.length ? <Table columns={['Member', 'Membership', 'Class', 'Payment', 'Booking', 'Created']} rows={rows} /> : <StateNotice state={bookings.state === 'ready' ? 'empty' : bookings.state} message={bookings.message} />}</SectionCard><SectionCard title="Upcoming schedule"><StateNotice state="unavailable" message="Schedule data is not exposed through a verified admin endpoint yet. No schedule has been inferred." /></SectionCard></div><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_1.4fr]"><SectionCard title="Pending actions"><div className="space-y-3 text-sm"><div className="flex items-center justify-between rounded-xl bg-secondary/60 p-4"><span>Offline payment verification</span><StatusBadge value="Unavailable" /></div><div className="flex items-center justify-between rounded-xl bg-secondary/60 p-4"><span>Health & Safety forms</span><StatusBadge value="Unavailable" /></div></div></SectionCard><SectionCard title="Quick actions"><div className="flex flex-wrap gap-3"><QuickLink href="/admin/members" label="View members" /><QuickLink href="/admin/bookings" label="View bookings" /><QuickLink href="/admin/schedule" label="View schedule" /><QuickLink href="/admin/memberships" label="View memberships" /><QuickLink href="/admin/payments" label="View payments" /></div></SectionCard></div></> }

function ResourcePage({ view }: { view: string }) { const config: Record<string, { title: string; eyebrow: string; description: string; endpoint: string }> = { members: { title: 'Members', eyebrow: 'Studio people', description: 'Member management will appear here when the protected admin members endpoint is available.', endpoint: '/api/admin/members' }, bookings: { title: 'Bookings', eyebrow: 'Studio operations', description: 'Review bookings returned by the existing member bookings endpoint. Admin-only actions remain unavailable until backend support exists.', endpoint: '/api/bookings/my' }, schedule: { title: 'Schedule', eyebrow: 'Weekly timetable', description: 'The weekly timetable will use verified schedule data only. Create, edit, and delete are intentionally disabled.', endpoint: '/api/admin/schedule' }, memberships: { title: 'Memberships', eyebrow: 'Commerce', description: 'Browse membership plans from the existing memberships endpoint. Management actions are read-only for this MVP.', endpoint: '/api/memberships' }, payments: { title: 'Payments', eyebrow: 'Commerce', description: 'Payment records and offline verification require protected admin payment endpoints.', endpoint: '/api/admin/payments' }, 'health-safety': { title: 'Health & Safety', eyebrow: 'Studio safety', description: 'Health & Safety records are admin-only and will appear when the protected endpoint is available.', endpoint: '/api/admin/health-safety' } }; const item = config[view] || config.members; return <><PageHeading eyebrow={item.eyebrow} title={item.title} description={item.description} /><SectionCard title={item.title}><StateNotice state={view === 'bookings' || view === 'memberships' ? 'loading' : 'unavailable'} message={view === 'bookings' || view === 'memberships' ? 'This view is wired to the existing API and will render its verified records here.' : `Waiting for ${item.endpoint}. No mock records or actions are shown.`} /></SectionCard></> }
