'use client'

import { useState } from 'react'

const screenings = ['Has a doctor or healthcare professional ever advised you not to exercise?', 'Do you currently have an injury, pain or physical limitation?', 'Do you experience unexplained chest pain or discomfort during exercise?', 'Do you experience dizziness, fainting or loss of balance?', 'Do you experience unusual shortness of breath during physical activity?', 'Do you have a diagnosed heart or cardiovascular condition?', 'Do you have high or low blood pressure?', 'Do you have asthma or another respiratory condition?', 'Do you have diabetes or blood sugar-related concerns?', 'Do you have osteoporosis or reduced bone density?', 'Do you have a neurological condition affecting movement, balance or coordination?', 'Do you have a joint, muscle, ligament or tendon condition?', 'Have you had surgery within the past 12 months?', 'Are you currently undergoing treatment or physical rehabilitation?', 'Are you currently taking medication that may affect your ability to exercise?']

function Field({ label, type = 'text' }: { label: string; type?: string }) { return <label className="block text-sm text-primary">{label}<input type={type} className="mt-2 w-full border border-border bg-background px-4 py-3 text-foreground outline-none focus:border-primary" /></label> }
function YesNo({ question }: { question: string }) { const [answer, setAnswer] = useState(''); return <div><p className="text-sm leading-6 text-primary">{question}</p><div className="mt-2 flex gap-2">{['Yes', 'No'].map(value => <button type="button" key={value} onClick={() => setAnswer(value)} className={`border px-4 py-2 text-sm ${answer === value ? 'border-primary bg-primary text-primary-foreground' : 'border-border text-primary hover:border-primary'}`}>{value}</button>)}</div>{answer === 'Yes' && <label className="mt-3 block border-l-2 border-accent pl-4 text-sm text-primary">Please provide details<textarea rows={3} className="mt-2 w-full border border-border bg-background px-4 py-3 text-foreground outline-none focus:border-primary" /></label>}</div> }

export default function HealthFormPage() { const [submitted, setSubmitted] = useState(false); return <main className="min-h-screen bg-muted/20 px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-3xl"><p className="text-xs uppercase tracking-[0.24em] text-accent">Sculpt LAB</p><h1 className="mt-3 font-serif text-4xl text-primary sm:text-5xl">Client Health & Exercise Readiness Form</h1><p className="mt-3 max-w-2xl text-base leading-7 text-muted-foreground">Please complete this form before participating in exercise. Optional information may be left blank; only answer what applies to you.</p>{submitted ? <section className="mt-8 border border-accent bg-background p-8"><h2 className="font-serif text-3xl text-primary">Form preview complete</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">This public page is a visual preview only. No information has been saved.</p><button type="button" onClick={() => setSubmitted(false)} className="mt-6 border border-primary px-5 py-3 text-sm text-primary">Review form</button></section> : <form onSubmit={event => { event.preventDefault(); setSubmitted(true) }} className="mt-8 space-y-8 border border-border bg-background p-6 sm:p-8"><div className="grid gap-4 sm:grid-cols-2"><Field label="Client Full Name" /><Field label="Email Address" type="email" /><Field label="Phone Number" /><Field label="Date of Birth" type="date" /><Field label="Age" type="number" /><Field label="Emergency Contact Name" /><Field label="Relationship" /><Field label="Emergency Contact Phone" /></div><section className="space-y-5"><h2 className="font-serif text-2xl text-primary">Pregnancy & postpartum</h2><YesNo question="Are you currently pregnant?" /><YesNo question="Have you recently given birth?" /></section><section className="space-y-5"><h2 className="font-serif text-2xl text-primary">Current health screening</h2>{screenings.map(question => <YesNo key={question} question={question} />)}</section><section className="space-y-5"><h2 className="font-serif text-2xl text-primary">Declaration</h2><p className="text-sm leading-6 text-muted-foreground">I confirm that the information I have provided is accurate and complete. I will communicate any changes in my health, pregnancy, injuries, or ability to exercise to my instructor.</p><label className="block text-sm text-primary">Signature<input required className="mt-2 w-full border border-border bg-background px-4 py-3 text-foreground outline-none focus:border-primary" /></label><label className="flex items-start gap-3 text-sm leading-6 text-primary"><input required type="checkbox" className="mt-1 size-4 accent-primary" />I agree to the declaration above.</label></section><button type="submit" className="bg-primary px-5 py-3 text-sm text-primary-foreground">Complete preview</button></form>}</div></main> }
